import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal = { "family" = "MesloLGL Nerd Font Mono", "style" = "Regular" }
# Use this for font smoothing. Will need to log out and back in to take effect.
# defaults write org.alacritty AppleFontSmoothing -int 0

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = true
blur = true

[window.padding]
x = 0
y = 0
