alias oldvim="vim"
alias vim="nvim"
alias vi="nvim"
# alias z="zoxide"
alias ccat="cat"
alias cat="bat"
alias ls="eza --icons=always"
alias l="eza --icons=always"
alias ll="eza -l --icons=always"
alias la="eza -la --icons=always"
alias lla="eza -la --icons=always"
alias lll="eza -l --tree --icons=always"
alias .cd="cd"
alias cd="z"
alias j="z"
alias .dc="dc"
alias dc="docker-compose"
