source "$XDG_CONFIG_HOME/zsh/secrets.zsh"
source "$XDG_CONFIG_HOME/zsh/env.zsh"
source "$XDG_CONFIG_HOME/zsh/config.zsh"
source "$XDG_CONFIG_HOME/zsh/alias.zsh"
source "$XDG_CONFIG_HOME/zsh/functions.zsh"
source "$XDG_CONFIG_HOME/zsh/private_functions.zsh"
